config/routes.rb
Rails.application.routes.draw do
  #resources :profiles

  devise_for :users, controllers: {registrations: 'registrations'}
  root to: "home#index"
   get 'profiles/liked_people/', to: 'profiles#liked_people', as: 'liked_people'
   get 'profiles/liked_user/', to: 'profiles#liked_user', as: 'liked_user'
  resources :profiles do
    post 'like',   to: 'socializations#like'
    post 'unlike', to: 'socializations#unlike'
  end

  post 'profiles/toggle_like/:profile_id', to: 'profiles#toggle_like', as: "toggle_like"

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	acts_as_liker
  acts_as_likeable

  #a like button on the cards
  #current_user.like!(user_whos_profile_is_beening_viewed)
  

  #user.unlike!(movie)
  #user.toggle_like!(celebrity)
  #user.likes?(movie)
  #movie.liked_by?(user)
  #movie.likers(User)
  def self.liked_people(current_user)
  	Profile.all.select{ |p| current_user.profile.likes?(p)}
  	
  end
   def self.liked_user(current_user)
  	Profile.all.select{ |p| p.likes?(current_user.profile)}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy

  validates_presence_of :user_name
  validates_uniqueness_of :user_name

  after_create :init_profile

  include Gravtastic
  gravtastic

  def init_profile
    Profile.create(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def show

  end

  def new

  end

  def edit

  end

  def create

  end

  def update
  	user = User.find(params[:id])
  	user.update(user_params)

  	redirect_to
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @gender_matches = Profile.where.not(gender: current_user.profile.gender)
  end

  def show
  	#@user = User.find(params[:id])
  	@profile = Profile.find(params[:id])
  end

	def new
		@profile = Profile.new
  end

  def create
  	if Profile.create(profile_params)
  		redirect_to profile_path
  	else
  		render :new
  	end
  end

  def edit
  	@profile = Profile.find(params[:id])
  end


  def update
  	@profile = Profile.find(params[:id])
  	if @profile.update(profile_params)
  		redirect_to profile_path
  	else
  		render :edit
  	end
  end

  private

  def profile_params
  	params.require(:profile).permit(:bio, :age, :gender, :city, :user_id, :user_likes)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @gender_matches = Profile.where.not(gender: current_user.profile.gender)
  end

  def show
  	#@user = User.find(params[:id])
  	@profile = Profile.find_by(user_id: params[:id])
  end

	def new
		@profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
  	if @profile.save
  		redirect_to profile_path(@profile)
  	else
  		render :new
  	end
  end

  def edit
  	@profile = Profile.find(params[:id])
  end


  def update
  	@profile = Profile.find(params[:id])
  	if @profile.update(profile_params)
  		redirect_to profile_path
  	else
  		render :edit
  	end
  end

  def destroy
    profile = Profile.find(params[:id])
    if profile.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  def toggle_like
  
    current_user.profile.toggle_like!( Profile.find(params[:profile_id]) )
    @gender_matches = Profile.where.not(gender: current_user.profile.gender)
   # binding.pry
    render :index
  end

  def liked_people
   # binding.pry
    @liked_people = Profile.liked_people(current_user)
    render :liked_people
  end
  def liked_user
     @liked_user = Profile.liked_user(current_user)
     render :liked_user
  end

  private

  def profile_params
  	params.require(:profile).permit(:bio, :age, :gender, :city, :user_id, :user_likes)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private
	
	def sign_up_params
		params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/index.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<div class='row'>
  <div class='col s10 offset-s1'>
	 	<div id='cancel'>	
			<%= link_to "Cancel my account", profile_path(current_user), method: :delete, class: "btn-large waves-effect waves-light" %>
			<br />
			<br />
			<div class="waves-effect waves-light btn-large"><%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
			</div>
		</div>
	  <div id='head'>
			<h2>Welcome <%= current_user.user_name %></h2>
				<%= image_tag current_user.gravatar_url %>
		</div>
		<br />
		<div class="text-align center">
		<h5>Search profiles to see other users.</h5>
		<h5>If this is your first time visiting, please <%= link_to "Edit Profile", edit_profile_path(current_user) %>.</h5>
		</div>
		<br />
	<%= link_to '*people you have licked*', liked_people_path%>
  <%= link_to '*people that have licked you*', liked_user_path%>
  <br />
		<div id='foot-home'>
			<%= link_to edit_profile_path(current_user) do %>
				<i class="material-icons large">settings_applications</i>
				<% end %>
		  <%= link_to profile_path(current_user) do %>
		  	<i class="material-icons large">person_pin</i>
				<% end %>
			<%= link_to profiles_path do %>
			  <i class="material-icons large">pageview</i>
				<% end %>
		</div>
		  <br />
		  <!-- take from views/devise/registrations/edit -->
		
		<br />
		
	</div>
</div>




>>>>>>> Arialle Commit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatingApp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	   <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<div class="row">
    <br />
    <br />
<div class="col s10 offset-s1" id='border'>
    <%= form_for @profile do |f| %>
    	<br />
    	<div class = "field">
    		<%= f.label :bio %>:
    		<%= f.text_field :bio %>
    	</div>
    	<br />
    	<div class = "field">
    		<%= f.label :age %>:
    		<%= f.number_field :age %>
    	</div>
    	<br />
    	<div class = "field">
    		<%= f.label :gender %>:
    		<%= f.radio_button :gender, 'Male' %>
        <%= f.label :gender, 'Male', value:'Male' %>
    		<%= f.radio_button :gender, 'Female' %>
        <%= f.label :gender, 'Female', value:'Female' %>
    	</div>
    	<br />
    	<div class = "field">
    		<%= f.label :city %>:
    		<%= f.text_field :city %>
    	</div>
    	<br />
    <div class="btn-large waves-effect waves-light">
        <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/profiles/edit.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<div class="row">
	<div class='col s10 offset-s1'>
		<div id='head'>
			<h1>Edit Profile</h1>
		</div>
		 <%= render(partial: 'form') %>
		 <br />
	<div id='foot'>
			<%= link_to root_path(current_user) do %>
		  	<i class="material-icons large">view_day</i>
				<% end %>
		  <%= link_to profile_path(current_user) do %>
		  	<i class="material-icons large">person_pin</i>
				<% end %>
			<%= link_to profiles_path do %>
			  <i class="material-icons large">pageview</i>
				<% end %>
		</div>
	</div>
</div>

app/views/profiles/index.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<h1>Browse Profiles</h1>
<hr />
<div class="row">
<% @gender_matches.each do |profile| %>
  <div class="col s4 offset-s1">
      <div class="card blue-grey">
        <p>Username: <%= "#{User.find(profile.user_id).user_name}" %></p>
        <p>Bio: <%= profile.bio %></p>
        <p>Age: <%= profile.age %></p>
        <p>Gender: <%= profile.gender %></p>
        <p>City: <%= profile.city %></p>
        <div class="card-action">
          <%= link_to "See #{User.find(profile.user_id).user_name}", profile_path(profile.user_id)%>
          <% if current_user.profile.likes?(Profile.find(profile)) %>
            <%= link_to "Un-Like ", toggle_like_path(profile), method: :post %>  
          <% else %>
            <%= link_to "Like #{User.find(profile.user_id).user_name}", toggle_like_path(profile), method: :post %>  
          <%end %> 
        <% end %>    
        </div>
      </div>
  </div>
  <div id='foot'>
    <%= link_to edit_profile_path(current_user) do %>
      <i class="material-icons large">settings_applications</i>
      <% end %>
    <%= link_to root_path(current_user) do %>
      <i class="material-icons large">view_day</i>
      <% end %>
    <%= link_to profile_path(current_user) do %>
        <i class="material-icons large">person_pin</i>
        <% end %>
    </div>
</div>

app/views/profiles/liked_people.html.erb
<h1>People you liked</h1>
<hr/>

<% if @liked_people.any? %>
<div class="row">
<% @liked_people.each do |profile| %>
  <div class="col s4 offset-s1">
      <div class="card blue-grey">
        <p>Username: <%= "#{User.find(profile.user_id).user_name}" %></p>
        <p>Bio: <%= profile.bio %></p>
        <p>Age: <%= profile.age %></p>
        <p>Gender: <%= profile.gender %></p>
        <p>City: <%= profile.city %></p>
        <div class="card-action">
          <%= link_to "See #{User.find(profile.user_id).user_name}", profile_path(profile.user_id)%>
          <% if current_user.profile.likes?(Profile.find(profile)) %>
            <%= link_to "Un-Like ", toggle_like_path(profile), method: :post %>  
          <% else %>
            <%= link_to "Like #{User.find(profile.user_id).user_name}", toggle_like_path(profile), method: :post %>  
          <%end %>     
        </div>
      </div>
  </div>
<% end %>
</div>

<% else %>
<p><%= "You don't like anyone :(" %></p>
<%end%>
<%= link_to 'Home Page', root_path %>

app/views/profiles/liked_user.html.erb
<h1>People that licked you</h1>
<hr/>

<% if @liked_user.any? %>
<div class="row">
<% @liked_user.each do |profile| %>
  <div class="col s4 offset-s1">
      <div class="card blue-grey">
        <p>Username: <%= "#{User.find(profile.user_id).user_name}" %></p>
        <p>Bio: <%= profile.bio %></p>
        <p>Age: <%= profile.age %></p>
        <p>Gender: <%= profile.gender %></p>
        <p>City: <%= profile.city %></p>
        <div class="card-action">
          <%= link_to "See #{User.find(profile.user_id).user_name}", profile_path(profile.user_id)%>
          <% if current_user.profile.likes?(Profile.find(profile)) %>
            <%= link_to "Un-Like ", toggle_like_path(profile), method: :post %>  
          <% else %>
            <%= link_to "Like #{User.find(profile.user_id).user_name}", toggle_like_path(profile), method: :post %>  
          <%end %>     
        </div>
      </div>
  </div>
<% end %>
</div>

<% else %>
<p><%= "No one likes you, Everybody hates you, you should eats worm :(" %></p>
<%end%>
<%= link_to 'Home Page', root_path %>

app/views/profiles/new.html.erb
<h1>Create Profile</h1>
<hr />
 <%= render(partial: 'form') %>

app/views/profiles/show.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<div class="row">
	<div class="col s10 offset-s1">
		<div id='head'>
	    <h1>Hello <%= "#{User.find(@profile.user_id).user_name}" %></h1>
	    <%= image_tag User.find(@profile.user_id).gravatar_url %>
		</div>
		<div class="text-align center">
			<h4>Bio:</h4>
			<p style="font-size: 24px"><%= @profile.bio %></p>
			<br />
		</div>
		<div class="col s4 text-align center">
			<h4>Age:</h4>
			<p style="font-size: 24px"><%= @profile.age %></p>
		</div>
		<div class="col s4 text-align center">
			<h4>Gender:</h4>
			<p style="font-size: 24px"><%= @profile.gender %></p>
		</div>
		<div class="col s4 text-align center">
			<h4>City:</h4>
			<p style="font-size: 24px"><%= @profile.city %></p>
		</div>
		<div id='foot'>
			<%= link_to edit_profile_path(current_user.profile) do %>
				<i class="material-icons large">settings_applications</i>
				<% end %>
		  <%= link_to root_path(current_user) do %>
		  	<i class="material-icons large">view_day</i>
				<% end %>
			<%= link_to profiles_path do %>
			  <i class="material-icons large">pageview</i>
				<% end %>
		</div>
	</div>
</div>